name: Deploy OTA firmware to GitHub Pages

on:
  release:
    types: [published]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Download firmware from release
        uses: dsaltares/fetch-gh-release-asset@v1.0.9
        with:
          file: firmware.bin # <-- Đúng tên file `.bin` trong release
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Clone gh-pages branch
        uses: actions/checkout@v4
        with:
          ref: gh-pages
          path: gh-pages

      - name: Copy firmware to gh-pages
        run: |
          cp firmware.bin gh-pages/firmware.bin

      - name: Commit and push to gh-pages
        run: |
          cd gh-pages
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"
          git add firmware.bin
          git commit -m "Update OTA firmware from latest release"
          git push origin gh-pages
