name: Deploy OTA firmware to GitHub Pages

on:
  release:
    types: [published]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Download firmware.bin from release
        uses: robinraju/release-downloader@v1.8
        with:
          tag: ${{ github.ref_name }}
          fileName: firmware.bin
          out-file-path: ./firmware/

      - name: Clone gh-pages branch
        uses: actions/checkout@v4
        with:
          ref: gh-pages
          path: gh-pages

      - name: Copy firmware to gh-pages
        run: cp ./firmware/firmware.bin gh-pages/

      - name: Commit and push to gh-pages
        run: |
          cd gh-pages
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"
          git add firmware.bin
          git commit -m "Update firmware from release ${{ github.ref_name }}"
          git push origin gh-pages
